### ISSUE TITLE
Linux Ubuntu error: No module named 'pyblake2'

### ISSUE THREAD

**Issue by cuteman18** [z-classic/electrum-zcl#109]
Dears,  
When I run ./electrum, I get error:

ImportError: No module named 'pyblake2'

I searched for pyblake2 (Python module), and istalled it .   Ans I still get the same error:   No module named 'pyblake2'.

I am on Linux Mint 18.1 .

**Comment by cuteman18** [comment]
I wonder when wallet developers will look into the issue.  After the fork?  :)

**Comment by ghost** [comment]
pip install pyblake2 on Ubuntu 17.10 should get it up and running. 

I had Please run 'pyrcc5 icons.qrc -o gui/qt/icons_rc.py', and reinstall Electrum
and it worked.

**Comment by cuteman18** [comment]
Did as you wrote :
(1)   electrum-zcl-Z-1.0.3 $ pip install pyblake2
**Requirement already satisfied: pyblake2 in /usr/local/lib/python2.7/dist-packages**

(2) 
**electrum-zcl-Z-1.0.3 $ pyrcc5 icons.qrc -o gui/qt/icons_rc.py**

Then I run ./electrum,  and get the same error: **No module named 'pyblake2'**  (see last line below) :
electrum-zcl-Z-1.0.3 $ ./electrum
Traceback (most recent call last):
  File "./electrum", line 88, in <module>
    imp.load_module('electrum', *imp.find_module('lib'))
  File "/usr/lib/python3.5/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.5/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/.../electrum-zcl-Z-1.0.3/lib/__init__.py", line 6, in <module>
    from .network import Network, pick_random_server
  File "/home/.../electrum-zcl-Z-1.0.3/lib/network.py", line 41, in <module>
    from . import blockchain
  File "/home/.../electrum-zcl-Z-1.0.3/lib/blockchain.py", line 33, in <module>
    from .equihash import is_gbp_valid
  File "/home/.../electrum-zcl-Z-1.0.3/lib/equihash.py", line 2, in <module>
    from pyblake2 import blake2b
ImportError: No module named 'pyblake2'

**Comment by ghost** [comment]
I think you need to install pyblake2 for Python3... Nevertheless... After pyblake2 is working, more errors will appear... I was not able to work around them... this wallet is not working
