### ISSUE TITLE
dumpprivkeys() command is not working to get private keys

### ISSUE THREAD

**Issue by Alternating** [z-classic/electrum-zcl#18]
>> dumpprivkeys()
"This command is deprecated. Use a pipe instead: 'electrum listaddresses | electrum getprivatekeys - '"
>> electrum listaddresses | electrum getprivatekeys
Traceback (most recent call last):
                         ^
SyntaxError: invalid syntax

**Comment by Alternating** [comment]
>> getprivatekeys()
Traceback (most recent call last):
  File "site-packages\electrum\commands.py", line 112, in _run
  File "site-packages\electrum\commands.py", line 87, in func_wrapper
TypeError: getprivatekeys() missing 1 required positional argument: 'address'
