### ISSUE TITLE
Cannot dump private key 

### ISSUE THREAD

**Issue by Alternating** [z-classic/electrum-zcl#19]
Closed previous github issue to make this one more detailed

>> getprivatekeys()
Traceback (most recent call last):
  File "site-packages\electrum\commands.py", line 112, in _run
  File "site-packages\electrum\commands.py", line 87, in func_wrapper
TypeError: getprivatekeys() missing 1 required positional argument: 'address'
>> getprivatekeys(t1apLXVhgFx77rmHsg2D613bTwcwyxxxxxx)
Traceback (most recent call last):
>> getprivatekeys()t1apLXVhgFx77rmHsg2D613bTwcwyxxxxxx
Traceback (most recent call last):
                                                      ^
SyntaxError: unexpected EOF while parsing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\electrum_gui\qt\console.py", line 222, in runCommand
  File "<string>", line 1
    getprivatekeys()t1apLXVhgFx77rmHsg2D613bTwcwyxxxxxx
                                                      ^
SyntaxError: invalid syntax
>> getprivatekeys() t1apLXVhgFx77rmHsg2D613bTwcwyxxxxxx
Traceback (most recent call last):
                                                       ^
SyntaxError: unexpected EOF while parsing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\electrum_gui\qt\console.py", line 222, in runCommand
  File "<string>", line 1
    getprivatekeys() t1apLXVhgFx77rmHsg2D613bTwcwyxxxxxx
                                                       ^
SyntaxError: invalid syntax

-----------------------------

>> dumpprivkeys()
"This command is deprecated. Use a pipe instead: 'electrum listaddresses | electrum getprivatekeys - '"
>> electrum getprivatekeys
Traceback (most recent call last):
                          ^
SyntaxError: unexpected EOF while parsing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\electrum_gui\qt\console.py", line 222, in runCommand
  File "<string>", line 1
    electrum getprivatekeys
                          ^
SyntaxError: invalid syntax

**Comment by Alternating** [comment]
Work around - go to the wallet drop down menu > private keys > Export - this works 100%  Not sure if the console commands have changed

**Comment by lzsaver** [comment]
```
getprivatekeys("t1WLWt6eo1ABK8rytB5jr6hbjBN7qavaxox")
"L2FaBrJtEagzNDQ9PZmNbTnUn8St6SHnegG6x3rGfVGWGmecsi8J"
```

**Comment by Mrwh0** [comment]
u using invalid systax  "SyntaxError: invalid syntax" read @izsaver msg is right syntax.

**Comment by ch4ot1c** [comment]
Parentheses in the console
