### ISSUE TITLE
Add instructions to readme for building a Mac .dmg

### ISSUE THREAD

**Issue by ch4ot1c** [z-classic/electrum-zcl#21]
We need to be able to build as a .dmg file for distribution. Documentation for this should be added in README.md.

**Comment by ch4ot1c** [comment]
Attempt so far on the .dmg, it generates but immediately closes with an error :( Have tried several other routes too; this is the closest to the documentation.

## Steps:
python3 setup.py install

### You Need to edit contrib/osx.spec:
-home = '/Users/voegtlin/electrum/'
+home = '/Users/Jon/Z/electrum-zcl/

pip3 install trezor btchip-python keepkey

### We are trying to: 
./contrib/make_packages
./contrib/make_osx
### (You have run them from the /electrum-zcl dir)

(Builds fine, creates .app and .dmg)

## Err:
Jon@Jons-MacBook-Pro:~/Z/electrum-zcl$ sudo ./dist/Electrum
Traceback (most recent call last):
  File "electrum.py", line 90, in <module>
    from electrum import bitcoin
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "electrum.py", line 90, in <module>
    from electrum import bitcoin
ImportError: cannot import name 'bitcoin'

**Comment by ch4ot1c** [comment]
Resolved; current Readme works. More buildsystem improvements coming as spesmilo/electrum rolls them out.
