### ISSUE TITLE
moduleNotFound error ubuntu 17.10

### ISSUE THREAD

**Issue by paOol** [z-classic/electrum-zcl#47]
followed linux instructions and when running ./electrum I get

```
~/electrum-zcl-Z-1.0.0                                                                                   
▶ ./electrum                            
Traceback (most recent call last):
  File "./electrum", line 88, in <module>
    imp.load_module('electrum', *imp.find_module('lib'))
  File "/usr/lib/python3.6/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.6/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/paool/electrum-zcl-Z-1.0.0/lib/__init__.py", line 6, in <module>
    from .network import Network, pick_random_server
  File "/home/paool/electrum-zcl-Z-1.0.0/lib/network.py", line 41, in <module>
    from . import blockchain
  File "/home/paool/electrum-zcl-Z-1.0.0/lib/blockchain.py", line 33, in <module>
    from .equihash import is_gbp_valid
  File "/home/paool/electrum-zcl-Z-1.0.0/lib/equihash.py", line 2, in <module>
    from pyblake2 import blake2b
ModuleNotFoundError: No module named 'pyblake2'


```

**Comment by ch4ot1c** [comment]
pip3 install pyblake2

**Comment by paOol** [comment]
ty, after doing so I also ran

`pyrcc5 icons.qrc -o gui/qt/icons_rc.py`

and got shown command not found, so I tried to install it and got this.

```
~/electrum-zcl-Z-1.0.0                                                                                  ⍉
▶ pip3 install pyrcc5
Collecting pyrcc5
  Could not find a version that satisfies the requirement pyrcc5 (from versions: )
No matching distribution found for pyrcc5

```

**Comment by paOol** [comment]
solved with 

` sudo apt-get install pyqt5-dev pyqt5-dev-tools -y`

**Comment by salim-b** [comment]
> pip3 install pyblake2

Just for completeness, all the necessary steps in one (this also works for Ubuntu 16.04 LTS):
```
sudo pip3 install pyblake2
sudo apt-get install pyqt5-dev pyqt5-dev-tools
pyrcc5 icons.qrc -o gui/qt/icons_rc.py
```
After that `./electrum` should work as expected ([v1.0.2](https://github.com/BTCP-community/electrum-zcl/archive/Z!1.0.2.tar.gz)).
